imagePullSecrets: {}

installation:
  enabled: true
  kubernetesProvider: ""
  calicoNetwork:
    bgp: Disabled
    ipPools:
    - natOutgoing: Enabled
      encapsulation: VXLAN
      cidr: 10.42.0.0/16

certs:
  node:
    key:
    cert:
    commonName:
  typha:
    key:
    cert:
    commonName:
    caBundle:

# Configuration for the tigera operator
tigeraOperator:
  image: tigera/operator
  version: v1.15.1
  registry: quay.io
calicoctl:
  image: quay.io/docker.io/calico/ctl
  tag: v3.18.1
